jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install OS image libs
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libopenjp2-7 libtiff5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test
